### ISSUE TITLE
Please upgrade Node.js to 16

### ISSUE THREAD

**Issue by StarpTech** [abelfodil/protoc-action#4]
We receive warnings in the CI

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: abelfodil/protoc-action

Would you accept a PR?

**Comment by abelfodil** [comment]
Yes!
